# Generated by Django 5.2.1 on 2026-06-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_courses_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='programme',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
